project:
  type: website
  output-dir: docs
  pre-render:
    - stlitepack_docs/make_test_index.py
    - stlitepack_docs/sync_docs.py
    - stlitepack_docs/run_tests.py
  # render:
  # - "!docs/**"
  render:
  - "*"
  - "!README.md"
  - "!PAGES_SETUP.md"
  - "!LICENCE.md"
  - "!CODE_OF_CONDUCT.md"
  - "!tests/README.md"

website:
  title: stlitepack
  description: "Documentation for the stlitepack streamlit packaging library"

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  dir: reference
  out_index: _api_index.qmd
  # the name used to import the package you want to create reference docs for
  package: stlitepack

  # write sidebar data to this file
  sidebar:
    file: "_sidebar.yml"
    style: docked
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Bergam0t/stlitepack
            target: _blank
          - text: Report a Bug
            href:  https://github.com/Bergam0t/stlitepack/issues
            target: _blank
      - icon: box-fill
        menu:
          - text: Download on pypi
            href: https://pypi.org/project/stlitepack/
            target: _blank

    search: true
    title: "stlitepack"
    subtitle: "A small package for turning Streamlit apps into stlite apps with minimal fuss"
    collapse-level: 2

    contents:
      - text: "Introduction"
        href: stlitepack_docs/index.qmd
      - text: "Quickstart Guide"
        href: stlitepack_docs/stlitepack_quickstart.qmd
      - section: "stlitepack Function Reference"
        contents:
          - "{{ contents }}"
      - text: "Tests"
        href: stlitepack_docs/test_outputs.qmd
      - text: "Licence"
        href: stlitepack_docs/licence.qmd
      - text: "Contributor Code of Conduct"
        href: stlitepack_docs/code_of_conduct.qmd

  sections:
    - title: Packing Functions
      desc: ""
      contents:
        - pack.pack
    - title: Publishing Functions
      desc: ""
      contents:
        - publish.setup_github_pages
    - title: Helper Functions
      desc: ""
      contents:
        - pack.get_stlite_versions

format:
  html:
    grid:
      sidebar-width: 325px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 1.5rem
    execute:
      freeze: auto
    theme:
      dark: [darkly, theme-dark.scss]
      light: [flatly, theme-light.scss]
